### ISSUE TITLE
LivenessProbe on / gives back a `write: connection reset by peer`

### ISSUE THREAD

**Issue by eyenx** [adfinis-sygroup/potz-holzoepfel-und-zipfelchape#60]
When using `/` as readinessProbe or livenessProbe, the container logs 

```
time="2024-02-23T14:27:26Z" level=info msg="Server is ready to handle requests at :8080"
time="2024-02-23T14:27:27Z" level=fatal msg="write tcp 10.100.145.121:8080->10.100.145.102:33082: write: connection reset by peer"
```
and goes into `CrashLoopBackOff`

I know the `probe` endpoint is under `/healthz` but `/` gives also back a HTTP 200 and I'm eager to know why this should not work with the probe.

**Comment by hairmare** [comment]
afair caasperli returns both the audio and image file as a bas64 island directly in the html source. my gut feeling is that this response from `/` is too large for the probe.
i'm not sure where this limit is defined, but the K8s' internal probe client is rather bare-bonesey, hence my theory.

**Comment by eyenx** [comment]
Thanks.
